//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by lnrc.rc
//
#define IDS_WINDOWTITLE                 1
#define IDR_VERSION1                    1
#define IDR_XPMANIFEST1                 1
#define IDR_ACCEL1                      1
#define IDC_FIND_FINDN                  1
#define IDC_AB_OK                       1
#define IDC_GT_GOTO                     1
#define IDC_CODE_OK                     1
#define IDC_TF_OK                       1
#define IDC_IA_OK                       1
#define IDS_CLASSNAME                   2
#define IDC_CM_CANCEL                   2
#define IDC_CF_CANCEL                   2
#define IDC_EA_CANCEL                   2
#define IDC_FIND_CANCEL                 2
#define IDC_RPC_CANCEL                  2
#define IDC_SS_CANCEL                   2
#define IDC_FONT_CLOSE                  2
#define IDC_AB_CANCEL                   2
#define IDC_GT_CANCEL                   2
#define IDC_CODE_CANCEL                 2
#define IDC_TF_CANCEL                   2
#define IDC_IA_CANCEL                   2
#define IDS_DEFAULTFONT                 3
#define IDS_CONFIGFILENAME              4
#define IDS_OPENTITLE3                  5
#define IDS_EXPORTTXT                   6
#define IDS_OPENTITLE1                  7
#define IDS_ERROPENDLG                  8
#define IDS_OPENTITLE2                  9
#define IDS_WRONGPOS                    11
#define IDS_ERRLOADFILE                 12
#define IDS_DLLERR                      13
#define IDS_FAILLOADMEL                 14
#define IDS_LOADINGMEL                  15
#define IDS_CANTOPENFILE                16
#define IDS_NOMATCH                     17
#define IDS_ERRMATCH                    18
#define IDS_ERREXDLL                    19
#define IDS_ERRSAVE                     20
#define IDS_SUCSAVE                     21
#define IDS_SAVEORNOT                   22
#define IDS_SUCEXPORT                   23
#define MANIFEST                        24
#define IDS_IMPORTTXT                   24
#define IDS_SUCIMPORT                   25
#define IDS_TXTUNICODE                  26
#define IDS_LINENOTMATCH                27
#define IDS_IMPORTPART                  28
#define IDS_STRTOOLONG                  29
#define IDS_DECLINEMOD                  30
#define IDS_NOMEM                       31
#define IDS_DEVELOP                     32
#define IDS_SHUAI                       33
#define IDS_CANTOPENCONFIG              34
#define IDS_NOTDEFMEL                   35
#define IDS_FAILIMPORT                  36
#define IDS_FAILEXPORT                  37
#define IDS_INVALIDDIR                  38
#define IDS_FAILREPLACE                 39
#define IDS_RPCCOMPLETE                 40
#define IDS_INNERNAME                   41
#define IDS_INNERVER                    42
#define IDS_INNERDESC                   43
#define IDS_INNERFORMAT                 44
#define IDS_SUCCONVERT                  45
#define IDS_FAILCONVERT                 46
#define IDS_SELECTBKGND                 47
#define IDS_ERRORCODE                   48
#define IDS_CODEFAILED                  49
#define IDS_CODECVTFAILED               50
#define IDS_LINEMODIFIED                51
#define IDS_LOGFILEOPENNOT              52
#define IDS_NOTSUPPORTBATCHEXP          53
#define IDS_NOTSUPPORTBATCHIMP          54
#define IDS_AUTOMATCH                   55
#define IDS_SELECTFILEAGAIN             56
#define IDS_LISTFILEVERSIONTOOLOW       57
#define IDS_FILTERPLUGINERR1            58
#define IDS_FILTERPLUGINERR2            59
#define IDD_CHOOSEMEL                   1000
#define IDC_CM_MELLIST                  1001
#define IDC_CM_STC1                     1002
#define IDC_CM_MELNAME                  1003
#define IDC_STC1                        1004
#define IDC_CM_VER                      1005
#define IDC_STC2                        1006
#define IDC_CM_DESC                     1007
#define IDC_STC3                        1008
#define IDC_CM_FORMAT                   1009
#define IDC_CM_OK                       1010
#define IDC_CM_REM                      1012
#define IDD_CONFIG                      1100
#define IDC_GRP8                        1101
#define IDC_CF_MODE_SINGLE              1102
#define IDC_CF_MODE_DOUBLE              1103
#define IDC_GRP9                        1104
#define IDC_CF_AUTOTIME                 1105
#define IDC_STC13                       1106
#define IDC_GRP10                       1107
#define IDC_CF_LOC_CURRENT              1108
#define IDC_CF_LOC_EXE                  1109
#define IDC_GRP11                       1110
#define IDC_CF_AC_NOT                   1111
#define IDC_CF_AC_FULL                  1112
#define IDC_CF_AC_HALF                  1113
#define IDC_CF_AUTOOPEN                 1114
#define IDC_CF_AUTOSELECT               1115
#define IDC_CF_OK                       1116
#define IDC_CF_SAVEWITHCODE             1117
#define IDC_STC18                       1118
#define IDC_CF_AUTOUPDATE               1119
#define IDD_EXPALL                      1200
#define IDC_GRP1                        1201
#define IDC_GRP2                        1202
#define IDC_GRP3                        1203
#define IDC_STC4                        1204
#define IDC_EA_NAME                     1205
#define IDC_STC6                        1206
#define IDC_EA_FORMAT                   1207
#define IDC_EA_CHGMEL                   1208
#define IDC_EA_DIRO                     1209
#define IDC_EA_BROWSEO                  1210
#define IDC_EA_DIRN                     1211
#define IDC_EA_BROWSEN                  1212
#define IDC_EA_OK                       1213
#define IDC_GRP12                       1214
#define IDC_EA_MELIDX                   1215
#define IDC_EA_CODE                     1216
#define IDC_STC16                       1217
#define IDC_STC17                       1218
#define IDC_EA_FORCEMEL                 1219
#define IDC_GRP17                       1220
#define IDC_EA_FILTERON                 1221
#define IDD_FIND                        1300
#define IDC_STC5                        1301
#define IDC_FIND_TEXT                   1302
#define IDC_FIND_FINDP                  1304
#define IDC_GRP4                        1306
#define IDC_FIND_WILD                   1307
#define IDC_FIND_REGU                   1308
#define IDC_FIND_TRAN                   1309
#define IDC_GRP5                        1310
#define IDC_FIND_ORI                    1311
#define IDC_FIND_NEW                    1312
#define IDD_REPLACE                     1400
#define IDC_STC7                        1401
#define IDC_STC8                        1402
#define IDC_RPC_FIND                    1403
#define IDC_RPC_RPC                     1404
#define IDC_RPC_FINDN                   1405
#define IDC_RPC_FINDP                   1406
#define IDC_RPC_REPLACE                 1407
#define IDC_RPC_RPCALL                  1409
#define IDD_SUMSEARCH                   1500
#define IDC_STC9                        1501
#define IDC_SS_TEXT                     1502
#define IDC_SS_MARK                     1503
#define IDC_SS_SEARCH                   1504
#define IDD_FONT                        1600
#define IDC_GRP6                        1601
#define IDC_FONT_LISTF                  1602
#define IDC_FONT_EDITF                  1603
#define IDC_GRP7                        1604
#define IDC_STC10                       1605
#define IDC_STC11                       1606
#define IDC_FONT_LISTCD                 1607
#define IDC_FONT_EDITC                  1608
#define IDC_STC12                       1611
#define IDC_FONT_LISTCS                 1612
#define IDD_ABOUT                       1700
#define IDC_STC26                       1701
#define IDC_STC27                       1702
#define IDC_STC28                       1703
#define IDC_AB_VER                      1704
#define IDC_STC30                       1705
#define IDD_GOTO                        1800
#define IDC_STC14                       1801
#define IDC_GT_LINE                     1802
#define IDC_STC15                       1803
#define IDC_GT_TOTAL                    1804
#define IDD_CODE                        1900
#define IDC_GRP13                       1901
#define IDC_STC19                       1902
#define IDC_CODE_OPEN1                  1903
#define IDC_STC20                       1904
#define IDC_CODE_OPEN2                  1907
#define IDC_GRP14                       1908
#define IDC_CODE_SAVE2                  1909
#define IDC_STC21                       1910
#define IDD_TXTFILTER                   2000
#define IDC_GRP15                       2001
#define IDC_TF_INON                     2002
#define IDC_TF_INPTN                    2003
#define IDC_STC22                       2004
#define IDC_TF_EXON                     2005
#define IDC_TF_EXPTN                    2006
#define IDC_STC23                       2007
#define IDC_GRP16                       2008
#define IDC_TF_HEADON                   2009
#define IDC_TF_HEADPTN                  2010
#define IDC_STC24                       2011
#define IDC_TF_TAILON                   2012
#define IDC_TF_TAILPTN                  2013
#define IDC_STC25                       2014
#define IDC_GRP24                       2015
#define IDC_TF_ALWAYSAPPLY              2016
#define IDC_TF_USEPLUGIN                2017
#define IDC_TF_PLUGINCOMBO              2018
#define IDC_TF_ALWAYSPLUGIN             2019
#define IDC_TF_PLUGINDESC               2020
#define IDD_IMPALL                      2100
#define IDC_GRP18                       2101
#define IDC_STC29                       2102
#define IDC_STC31                       2103
#define IDC_IA_NAME                     2104
#define IDC_IA_FORMAT                   2105
#define IDC_IA_FORCEMEL                 2106
#define IDC_IA_CHGMEL                   2107
#define IDC_GRP19                       2108
#define IDC_GRP20                       2109
#define IDC_IA_FILTERON                 2110
#define IDC_STC32                       2111
#define IDC_STC33                       2112
#define IDC_IA_CODE                     2113
#define IDC_GRP21                       2114
#define IDC_GRP22                       2115
#define IDC_IA_MELIDX                   2116
#define IDC_IA_DIRO                     2118
#define IDC_IA_BROWSEO                  2119
#define IDC_IA_BROWSEN                  2120
#define IDC_IA_DIRN                     2121
#define IDD_OPENTML                     2200
#define IDC_STC34                       2201
#define IDC_OPEN_PLUGINS                2202
#define IDD_PROGBAR                     2300
#define IDC_PRBAR_BAR                   2301
#define IDC_PRBAR_STOP                  2302
#define IDR_MMENU_CHS                   10000
#define IDM_OPEN                        10001
#define IDM_LOAD                        10002
#define IDM_SAVE                        10003
#define IDM_SAVEAS                      10004
#define IDM_CLOSE                       10005
#define IDM_SETCODE                     10006
#define IDM_EXPORT                      10007
#define IDM_IMPORT                      10008
#define IDM_EXIT                        10009
#define IDM_UNDO                        10011
#define IDM_REDO                        10012
#define IDM_MODIFY                      10013
#define IDM_PREVTEXT                    10014
#define IDM_NEXTTEXT                    10015
#define IDM_MARK                        10016
#define IDM_PREVMARK                    10017
#define IDM_NEXTMARK                    10018
#define IDM_FIND                        10019
#define IDM_REPLACE                     10020
#define IDM_SUMMARY                     10021
#define IDM_GOTO                        10022
#define IDM_GOTO2                       10022
#define IDM_FONT                        10024
#define IDM_BACKGROUND                  10025
#define IDM_CUSTOMUI                    10026
#define IDM_RECOVERUI                   10027
#define IDM_EXALL                       10029
#define IDM_IMALL                       10030
#define IDM_SUMALL                      10031
#define IDM_CONFIG                      10033
#define IDM_ABOUT                       10035
#define IDM_CVTFULL                     10037
#define IDM_CVTHALF                     10038
#define IDM_UNMARKALL                   10039
#define IDM_PROGRESS2                   10040
#define IDM_PROGRESS                    10040
#define IDM_TXTFILTER                   10041

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
