      include \masm32\include\windows.inc
      include \masm32\include\masm32.inc      
      include \masm32\include\gdi32.inc
      include \masm32\include\user32.inc
      include \masm32\include\kernel32.inc
      include \masm32\include\Comctl32.inc
      include \masm32\include\comdlg32.inc
      include \masm32\include\shell32.inc
      include \masm32\include\oleaut32.inc
      include \masm32\include\msvcrt.inc
      include \masm32\include\shlwapi.inc
      include \masm32\macros\macros.asm
      include \masm32\macros\strings.mac

      includelib \masm32\lib\masm32.lib
      includelib \masm32\lib\gdi32.lib
      includelib \masm32\lib\user32.lib
      includelib \masm32\lib\kernel32.lib
      includelib \masm32\lib\Comctl32.lib
      includelib \masm32\lib\comdlg32.lib
      includelib \masm32\lib\shell32.lib
      includelib \masm32\lib\oleaut32.lib
      includelib \masm32\lib\shlwapi.lib
      includelib \masm32\lib\msvcrt.lib
      
	include \masm32\lneditor\plugin.inc
	include \masm32\lneditor\export.inc
	include \masm32\lneditor\rsrc.inc
	include \masm32\lneditor\config.inc
	includelib \masm32\lneditor\lnedit.lib
	
N2Index struct
	hMap		dd		?
	lpMapStream	dd		?
	nStreamSize	dd		?
	lpIndex		dd		?
	nIndex		dd		?
	bWritable	dd		?
N2Index ends

Release proto :dword
N2DirFileNameW proto :dword

.data?
	hInstance		dd		?
	hHeap		dd		?
	
	lpMapFile	dd		?

	dwTemp		dd		?
.const
	TW		"Can\-t open the Map file, please place ",	szNoMapFile
	TW0		"the .map file to the same folder.\n"
	TW0		'N2System',	szInnerName
	
	
		